name:                saucy
version:             0.1.0.0
github:              "kev-liao/saucy"
license:             BSD3
author:              "Kevin Liao"
maintainer:          "kliao6@illinois.edu"
copyright:           "Copyright (c) 2018 Kevin Liao"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- ansi-wl-pprint
- base
- containers
- text
- parsec
- placeholders
- pretty
- transformers
- haskeline
- mtl
- optparse-applicative
- repline
- silently


library:
  source-dirs: src

executables:
  saucy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saucy

tests:
  saucy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saucy
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
